all: PruferFromTree TreeFromPrufer
PruferFromTree: PruferFromTree.cpp
	g++ -std=c++11 -pedantic -pthread PruferFromTree.cpp -o PruferFromTree
TreeFromPrufer: TreeFromPrufer.cpp
	g++ -std=c++11 -pedantic -pthread TreeFromPrufer.cpp -o TreeFromPrufer
